MVC_Redis/Models/CacheRequestModel.cs
namespace MVC_Redis.Models
{
    public class CacheRequestModel
    {
        public string Key { get; set; }
        public string Value { get; set; }
    }
}

MVC_Redis/Models/CategoryModel.cs
namespace MVC_Redis.Models
{
    public class CategoryModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

MVC_Redis/Models/ErrorViewModel.cs
namespace MVC_Redis.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC_Redis/Controllers/AccountController.cs
using Entities.Dto.AccountModel;
using Microsoft.AspNetCore.Mvc;

namespace MVC_Redis.Controllers
{
    public class AccountController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		[HttpGet]
		public IActionResult Register()
		{
			return View();
		}


		[HttpPost]
		public IActionResult Register(Register register )
        {

            TempData["PhoneNumber"] = register.PhoneNumber;
            return RedirectToAction("SmsConfirmation");
        }

        [HttpGet]
        public IActionResult SmsConfirmation()
        {
            return View(new SmsConfirmation() { PhoneNumber = TempData["PhoneNumber"].ToString() }) ;
        }


        [HttpPost]
        public IActionResult SmsConfirmation(SmsConfirmation smsConfirmation)
        {
            return View();
        }

        [HttpPost]
        public JsonResult IsAlreadySigned(string PhoneNumber)
        {
			//yoksa true
			//varsa false
            return Json(true);

        }
    }
}

MVC_Redis/Controllers/BasketController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC_Redis.Controllers
{
	public class BasketController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		
	}
}

MVC_Redis/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC_Redis.Controllers
{
    //[Route("api")]
    //[ApiController]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly ILogger<CategoryController> _logger;

        public CategoryController(ICategoryService categoryService, ILogger<CategoryController> logger)
        {
            _categoryService = categoryService;
            _logger = logger;
        }
        //[HttpGet("category/getall")]
        //public IActionResult GetAll()
        //{
        //    return Ok(_categoryService.GetAllCategory());
        //}
      
        public IActionResult Index()
        {
            return View();
        }
      
        public IActionResult GetAll()
        {

            var test = _categoryService.GetAllCategory();
            return View();
        }
    }
}

MVC_Redis/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC_Redis.Controllers
{
    public class CoursesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

		public IActionResult LoadPartial(string view)
		{

			return PartialView("_" + view);
		}
	}
}

MVC_Redis/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Redis.Models;
using System.Diagnostics;

namespace MVC_Redis.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC_Redis/Controllers/InstructorController.cs
using Entities.Dto.AccountModel;
using Entities.Dto.ProfileModel;
using Microsoft.AspNetCore.Mvc;

namespace MVC_Redis.Controllers
{
    public class InstructorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Profile()
        {
            return View();
        }

        [HttpPost]
		public IActionResult Profile(InstructorProfile  instructorProfile)
		{
            //Profile Kayıt

			
			return View();
		}

		public IActionResult Instructor()
		{
			return View();
		}

		public IActionResult LoadPartial(string view)
        {
           
            return PartialView("_"+view);
        }

        public IActionResult LoadModalPartial()
        {

            return PartialView("_AddCoursePartialView");
        }
    }
}

MVC_Redis/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC_Redis.Controllers
{
	public class PaymentController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Invoice()
		{
			return View();
		}
	}
}

MVC_Redis/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC_Redis.Controllers
{
    public class SearchController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVC_Redis/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVC_Redis.Controllers
{
	public class StudentController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Profile()
		{
			return View();
		}

        public IActionResult LoadPartial(string view)
        {

            return PartialView("_" + view);
        }
    }
}

MVC_Redis/Views/Courses/_CurriculumPartialView.cshtml
<div class="mb-4">
	<h5 class="">1. Marketing Fundamentals</h5>
	<p class="mb-0"> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
</div>
<div class="mb-4">
	<h5 class="">2. Social Media Marketing</h5>
	<p class="mb-0"> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
</div>
<div class="mb-4">
	<h5 class="">3. Search Engine Optimization (SEO)</h5>
	<p class="mb-0"> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
</div>
<div class="mb-4">
	<h5 class="">4. Specialisation in Marketing Analytics</h5>
	<p class="mb-0"> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
</div>
<div>
	<h5 class="">5.Specialisation in Social Media and Content Marketing</h5>
	<p class="mb-0"> Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
</div>

MVC_Redis/Views/Courses/_InstructorPartialView.cshtml
<div class="card mb-0 border-0 shadow-none">
	<div class="card-body item-user p-0">
		<div class="profile-pic mb-0 text-start">
			<div class="d-md-flex d-block">
				<img src="../assets/images/users/female/20.jpg" class="brround me-5" alt="user">
				<div class="my-auto">
					<a href="userprofile.html" class="text-dark"><h4 class="mb-1 font-weight-semibold">Julia Hardacre</h4></a>
					<span class="text-muted">Member Since November 2008</span>
					<div class=" item-user-icons mt-1">
						<a href="javascript:void(0)" class="facebook-bg mt-0"><i class="fa fa-facebook"></i></a>
						<a href="javascript:void(0)" class="twitter-bg"><i class="fa fa-twitter"></i></a>
						<a href="javascript:void(0)" class="google-bg"><i class="fa fa-google"></i></a>
						<a href="javascript:void(0)" class="dribbble-bg"><i class="fa fa-dribbble"></i></a>
					</div>
				</div>
			</div>
			<div class="description">
				<p class="lead-1 mb-0 mt-5">
					Ut enim ad minim veniam, quis Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et  nostrud exercitation ullamco laboris   commodo consequat.
				</p>
			</div>
		</div>
	</div>
	<div class="card-body border-top-0 item-user ps-0 pr-0 pb-0">
		<h4 class="mb-4">Contact Info</h4>
		<div>
			<h6 class="mb-3"><span class="font-weight-semibold"><i class="fe fe-map-pin me-2 mb-2"></i></span><a href="javascript:void(0)" class="text-body"> 7981 Aspen Ave. Hammonton,  USA</a></h6>
			<h6 class="mb-3"><span class="font-weight-semibold"><i class="fe fe-mail me-2 mb-2"></i></span><a href="javascript:void(0)" class="text-body"> smith@gmail.com</a></h6>
			<h6 class="mb-3"><span class="font-weight-semibold"><i class="fe fe-phone me-2  mb-2"></i></span><a href="javascript:void(0)" class="text-body"> 0-235-657-24587</a></h6>
			<h6 class="mb-0"><span class="font-weight-semibold"><i class="fe fe-link me-2 "></i></span><a href="javascript:void(0)" class="text-body">http://abcd.com/</a></h6>
		</div>
	</div>
</div>

MVC_Redis/Views/Instructor/_EditProfilePartialView.cshtml
@model Entities.Dto.ProfileModel.InstructorProfile


<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script src="~/assets/plugins/select2/select2.full.min.js"></script>
<script src="~/assets/js/select2.js"></script>
@using (Html.BeginForm("Profile", "Instructor", FormMethod.Post))
{

    <div class="card border-0 shadow-none mb-0">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-6 col-md-6">
                    <div class="form-group">
                        <label class="form-label">Ad</label>
                        @Html.TextBoxFor(e => e.FirstName, new { @class = "form-control", placeholder = "Ad" })
                        @Html.ValidationMessageFor(e => e.FirstName,"",new { @style="color:red" })
                    </div>
                </div>
                <div class="col-sm-6 col-md-6">
                    <div class="form-group">
                        <label class="form-label">Soyad</label>
                        @Html.TextBoxFor(e => e.LastName, new { @class = "form-control", placeholder = "Soyad" })
                        @Html.ValidationMessageFor(e => e.LastName,"",new { @style="color:red" })
                    </div>
                </div>
                <div class="col-sm-6 col-md-6">
                    <div class="form-group">
                        <label class="form-label">E-Posta</label>
                        @Html.TextBoxFor(e => e.Email, new { @class = "form-control", placeholder = "E-Posta" })
                        @Html.ValidationMessageFor(e => e.Email,"",new { @style="color:red" })
                    </div>
                </div>
                <div class="col-sm-6 col-md-6">
                    <div class="form-group">
                        <label class="form-label">Telefon</label>
                        @Html.TextBoxFor(e => e.PhoneNumber, new { @class = "form-control", placeholder = "Telefon Numarası" })
                        @Html.ValidationMessageFor(e => e.PhoneNumber,"",new { @style="color:red" })
                    </div>
                </div>

                <div class="col-sm-6 col-md-6">
                    <div class="form-group">
                        <label class="form-label">Şehir</label>
                        @Html.TextBoxFor(e => e.City, new { @class = "form-control", placeholder = "Şehir" })
                        @Html.ValidationMessageFor(e => e.City,"",new { @style="color:red" })
                    </div>
                </div>

                <div class="col-sm-6 col-md-6">
                    <div class="form-group">
                        <label class="form-label">Ülke</label>
                        <select class="form-control select2-show-search border-bottom-0 w-100 select2-show-search select2-hidden-accessible" data-placeholder="Select" data-select2-id="9" tabindex="-1" aria-hidden="true" name="Country" id="Country">
                            <optgroup label="Ülke" data-select2-id="26">

                                <option value="0" data-select2-id="27">Türkiye</option>
                                <option value="1" data-select2-id="28">Germany</option>
                                <option value="2" data-select2-id="29">Real Estate</option>
                                <option value="3" data-select2-id="30">Canada</option>
                                <option value="4" data-select2-id="31" selected="">Usa</option>
                                <option value="5" data-select2-id="32">Afghanistan</option>
                                <option value="6" data-select2-id="33">Albania</option>
                                <option value="7" data-select2-id="34">China</option>
                                <option value="8" data-select2-id="35">Denmark</option>
                                <option value="9" data-select2-id="36">Finland</option>
                                <option value="10" data-select2-id="37">India</option>
                                <option value="11" data-select2-id="38">Kiribati</option>
                                <option value="12" data-select2-id="39">Kuwait</option>
                                <option value="13" data-select2-id="40">Mexico</option>
                                <option value="14" data-select2-id="41">Pakistan</option>
                            </optgroup>
                        </select>
                    </div>
                </div>
                <div class="col-sm-6 col-md-6">
                    <div class="form-group">
                        <label class="form-label">Facebook</label>
                        @Html.TextBoxFor(e => e.Facebook, new { @class = "form-control", placeholder = "https://www.facebook.com/" })
                        @Html.ValidationMessageFor(e => e.Facebook,"",new { @style="color:red" })
                       
                    </div>
                </div>
                <div class="col-sm-6 col-md-6">
                    <div class="form-group">
                        <label class="form-label">Google</label>
                       
                        @Html.TextBoxFor(e => e.Google, new { @class = "form-control", placeholder = "https://www.google.com/" })
                        @Html.ValidationMessageFor(e => e.Google,"",new { @style="color:red" })
                    </div>
                </div>
                <div class="col-sm-6 col-md-6">
                    <div class="form-group">
                        <label class="form-label">Twitter</label>
                      
                        @Html.TextBoxFor(e => e.Twitter, new { @class = "form-control", placeholder = "https://twitter.com/" })
                        @Html.ValidationMessageFor(e => e.Twitter,"",new { @style="color:red" })
                    </div>
                </div>
                <div class="col-sm-6 col-md-6">
                    <div class="form-group">
                        <label class="form-label">Web</label>
                        @Html.TextBoxFor(e => e.Web, new { @class = "form-control", placeholder = "https://www." })
                        @Html.ValidationMessageFor(e => e.Web,"",new { @style="color:red" })
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="form-group">
                        <label class="form-label">Diller</label>
                        <select class="form-control select2" data-placeholder="Choose Browser" name="Languages" id="Languages" multiple>
                            <option value="TR">
                                Türkçe
                            </option>
                            <option value="EN selected">
                                İngilizce
                            </option>
                            <option value="GER">
                                Almanca
                            </option>
                            <option selected value="ITA">
                                Italyanca
                            </option>
                            <option value="FR">
                                Fransızca
                            </option>
                        </select>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="form-label">Hakkımda</label>
                        @Html.TextAreaFor(e=>e.About , new {@class="form-control",rows="5",placeholder="Açıklama"})
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="input-group file-browser">
                        <input type="text" class="form-control border-end-0 browse-file valid" placeholder="Upload Images" readonly="" aria-invalid="false" value="colorful-logo-icons.png">
                        <label class="input-group-btn">
                            <span class="btn btn-primary">
                                Browse <input type="file" style="display: none;" multiple="">
                            </span>
                        </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer border-top-0">
            <button type="submit" class="btn btn-primary">Updated Profile</button>
        </div>
    </div>




}

MVC_Redis/Views/Search/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section Header {

	<div>
		<div class="sptb-1">
			<div class="header-text1 mb-0">
				<div class="container">
					<div class="row">
						<div class="col-xl-9 col-lg-12 col-md-12 d-block mx-auto">
							<div class="text-center text-white text-property">
								<h1 class=""><span class="font-weight-bold">2000+</span> En İyi Eğitmenler ve Kurslar Burada!</h1>
							</div>
							<div class="search-background bg-transparent">
								<div class="form row g-0 ">
									<div class="form-group  col-xl-4 col-lg-3 col-md-12 mb-0 bg-white">
										<input type="text" class="form-control input-xl br-te-md-0 br-be-md-0 border-end-0" id="text4" placeholder="Eğitmen Ara.....">
									</div>
									<div class="form-group  col-xl-3 col-lg-3 col-md-12 mb-0 bg-white">
										<input type="text" class="form-control input-xl br-md-0 border-end-0" id="text5" placeholder="Konum Gir">
										<span><i class="fa fa-map-marker location-gps me-1"></i> </span>
									</div>
									<div class="form-group col-xl-3 col-lg-3 col-md-12 select2-lg mb-0 bg-white">
										<select class="form-control select2-show-search  border-bottom-0" data-placeholder="Select Category">
											<optgroup label="Kategori">
												<option>Kategori Seç </option>
												<option value="1">IT</option>
												<option value="2">Language</option>
												<option value="3">Science</option>
												<option value="4">Health</option>
												<option value="5">Humanities</option>
												<option value="6">Business</option>
												<option value="7">Maths</option>
												<option value="8">Marketing</option>
											</optgroup>
										</select>
									</div>
									<div class="col-xl-2 col-lg-3 col-md-12 mb-0">
										<a href="javascript:void(0)" class="btn btn-xl btn-block btn-secondary br-ts-md-0 br-bs-md-0" onclick="getPartialView()">Ara</a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div><!-- /header-text -->
		</div>
	</div><!--/Section-->

}

<section class="sptb">
	<div class="container">
		<div class="row">
			<!--Left Side Content-->
			<div class="col-xl-3 col-lg-4 col-md-12">
				<div class="card">
					<div class="card-body">
						<div class="input-group">
							<input type="text" class="form-control br-ts-7 br-bs-7" placeholder="Ara">
							<div class="input-group-text ">
								<button type="button" class="btn btn-primary br-te-7 br-be-7">
									Ara
								</button>
							</div>
						</div>
					</div>
				</div>
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Kategori</h3>
					</div>
					<div class="card-body">
						<div class="" id="container">
							<div class="filter-product-checkboxs">
								<label class="custom-control form-checkbox mb-3">
									<input type="checkbox" class="custom-control-input" name="checkbox1" value="option1">
									<span class="custom-control-label">
										<a href="javascript:void(0)" class="text-dark">İşletme<span class="label label-primary br-7 float-end">14</span></a>
									</span>
								</label>
								<label class="custom-control form-checkbox mb-3">
									<input type="checkbox" class="custom-control-input" name="checkbox2" value="option2">
									<span class="custom-control-label">
										<a href="javascript:void(0)" class="text-dark">Veri Bilimi<span class="label label-primary br-7 float-end">22</span></a>
									</span>
								</label>
								<label class="custom-control form-checkbox mb-3">
									<input type="checkbox" class="custom-control-input" name="checkbox3" value="option3">
									<span class="custom-control-label">
										<a href="javascript:void(0)" class="text-dark">IT<span class="label label-primary br-7 float-end">78</span></a>
									</span>
								</label>
								<label class="custom-control form-checkbox mb-3">
									<input type="checkbox" class="custom-control-input" name="checkbox4" value="option3">
									<span class="custom-control-label">
										<a href="javascript:void(0)" class="text-dark">Pazarlama<span class="label label-primary br-7 float-end">35</span></a>
									</span>
								</label>
								<label class="custom-control form-checkbox mb-3">
									<input type="checkbox" class="custom-control-input" name="checkbox5" value="option3">
									<span class="custom-control-label">
										<a href="javascript:void(0)" class="text-dark">Matematik<span class="label label-primary br-7 float-end">23</span></a>
									</span>
								</label>
								<label class="custom-control form-checkbox mb-3">
									<input type="checkbox" class="custom-control-input" name="checkbox6" value="option3">
									<span class="custom-control-label">
										<a href="javascript:void(0)" class="text-dark">Fotoğrafçılık<span class="label label-primary br-7 float-end">14</span></a>
									</span>
								</label>
								<label class="custom-control form-checkbox mb-3">
									<input type="checkbox" class="custom-control-input" name="checkbox7" value="option3">
									<span class="custom-control-label">
										<a href="javascript:void(0)" class="text-dark">Edebiyat<span class="label label-primary br-7 float-end">45</span></a>
									</span>
								</label>
								<label class="custom-control form-checkbox mb-3">
									<input type="checkbox" class="custom-control-input" name="checkbox7" value="option3">
									<span class="custom-control-label">
										<a href="javascript:void(0)" class="text-dark">Hukuk<span class="label label-primary br-7 float-end">34</span></a>
									</span>
								</label>
								<label class="custom-control form-checkbox mb-3">
									<input type="checkbox" class="custom-control-input" name="checkbox7" value="option3">
									<span class="custom-control-label">
										<a href="javascript:void(0)" class="text-dark">Sağlık<span class="label label-primary br-7 float-end">12</span></a>
									</span>
								</label>
								<label class="custom-control form-checkbox mb-3">
									<input type="checkbox" class="custom-control-input" name="checkbox7" value="option3">
									<span class="custom-control-label">
										<a href="javascript:void(0)" class="text-dark">Dijital Pazarlama<span class="label label-primary br-7 float-end">18</span></a>
									</span>
								</label>
								<label class="custom-control form-checkbox mb-3">
									<input type="checkbox" class="custom-control-input" name="checkbox7" value="option3">
									<span class="custom-control-label">
										<a href="javascript:void(0)" class="text-dark">Web Tasarım<span class="label label-primary br-7 float-end">02</span></a>
									</span>
								</label>
								<label class="custom-control form-checkbox mb-3">
									<input type="checkbox" class="custom-control-input" name="checkbox7" value="option3">
									<span class="custom-control-label">
										<a href="javascript:void(0)" class="text-dark">Diller<span class="label label-primary br-7 float-end">15</span></a>
									</span>
								</label>
								<label class="custom-control form-checkbox mb-3">
									<input type="checkbox" class="custom-control-input" name="checkbox7" value="option3">
									<span class="custom-control-label">
										<a href="javascript:void(0)" class="text-dark">Uygulama Geliştiricisi<span class="label label-primary br-7 float-end">32</span></a>
									</span>
								</label>
							</div>
						</div>
					</div>
					<div class="card-header border-top">
						<h3 class="card-title">Seviyeler</h3>
					</div>
					<div class="card-body">
						<div class="filter-product-checkboxs">
							<label class="custom-control form-checkbox mb-2">
								<input type="checkbox" class="custom-control-input" name="checkbox11" value="option1">
								<span class="custom-control-label">
									Başlangıç
								</span>
							</label>
							<label class="custom-control form-checkbox mb-2">
								<input type="checkbox" class="custom-control-input" name="checkbox12" value="option2">
								<span class="custom-control-label">
									Orta düzey
								</span>
							</label>
							<label class="custom-control form-checkbox mb-0">
								<input type="checkbox" class="custom-control-input" name="checkbox13" value="option3">
								<span class="custom-control-label">
									Gelişmiş
								</span>
							</label>
						</div>
					</div>
					<div class="card-header border-top">
						<h3 class="card-title">Kurs Tipi</h3>
					</div>
					<div class="card-body">
						<div class="filter-product-checkboxs">
							<label class="custom-control form-checkbox mb-2">
								<input type="checkbox" class="custom-control-input" name="checkbox1" value="option1">
								<span class="custom-control-label">
									Ücretsiz
								</span>
							</label>
							<label class="custom-control form-checkbox mb-0">
								<input type="checkbox" class="custom-control-input" name="checkbox2" value="option2">
								<span class="custom-control-label">
									Ücretli
								</span>
							</label>
						</div>
					</div>
					<div class="card-header border-top">
						<h3 class="card-title">Süre</h3>
					</div>
					<div class="card-body">
						<div class="filter-product-checkboxs">
							<label class="custom-control form-checkbox mb-2">
								<input type="checkbox" class="custom-control-input" name="checkbox1" value="option1">
								<span class="custom-control-label">
									+5saat
								</span>
							</label>
							<label class="custom-control form-checkbox mb-2">
								<input type="checkbox" class="custom-control-input" name="checkbox2" value="option2">
								<span class="custom-control-label">
									+10saat
								</span>
							</label>
							<label class="custom-control form-checkbox mb-2">
								<input type="checkbox" class="custom-control-input" name="checkbox2" value="option3">
								<span class="custom-control-label">
									+20saat
								</span>
							</label>
							<label class="custom-control form-checkbox mb-0">
								<input type="checkbox" class="custom-control-input" name="checkbox2" value="option4">
								<span class="custom-control-label">
									+30saat
								</span>
							</label>
						</div>
					</div>
					<div class="card-footer">
						<a href="javascript:void(0)" class="btn btn-primary btn-block">Filtreyi Uygula</a>
					</div>
				</div>
			</div>
			<!--/Left Side Content-->
			<!--Coursed Lists-->
			<div class="col-xl-9 col-lg-8 col-md-12" id="tab-11">
				<!--Coursed lists-->
				
				<!--/Coursed lists-->
			</div>
			<!--/Coursed Lists-->
		</div>
	</div>
</section>
<!--/Coursed Listing-->
<script>



	function getPartialView()
  {
      var link='@Url.Action("LoadPartial","Search")';
      
        $.get(link , function (data) {
            
            $('#tab-11').html(data);
        });
      
  }





</script>

MVC_Redis/Views/Shared/Footer/_Subscribe.cshtml
<section class="cover-image sptb bg-background-1" data-bs-image-src="/assets/images/banners/banner5.jpg">
	<div class="content-text mb-0">
		<div class="content-text mb-0">
			<div class="container">
				<div class="text-white">
					<div class="row">
						<div class="col-lg-6">
							<div class="mt-0">
								<h1 class="mb-2 font-weight-semibold">Abone Ol</h1>
								<p class="fs-18 mb-0">Bizden haber ve duyruları almak istiyorsan e-posta adresini bizimle paylaş.</p>
							</div>
						</div>
						<div class="col-lg-6">
							<div class="mt-4">
								<div class="input-group sub-input mt-1">
									<input type="text" class="form-control input-lg  br-ts-7  br-bs-7" placeholder="E-posta">
									<div class="input-group-text ">
										<button type="button" class="btn btn-secondary btn-lg br-te-7  br-be-7">
											Abone ol
										</button>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

MVC_Redis/Views/Shared/NavMenu/_Loader.cshtml
<div id="global-loader">
    <img src="~/assets/images/loader.svg" class="loader-img" alt="img">
</div>